# -*- coding: utf-8 -*-
"""Il nome pulito di ogni istituto statale di riferimento, e le parole del suo nome da togliere dai
nomi dei plessi (dove il Ministero le ripete davanti al nome vero del plesso)."""

ISTITUTI = {
    # Avellino
    "AVIC842008": ("IC Mons. Pasquale Guerriero", r"MONS\.?\s*P\.?\s*GUERRIERO"),
    "AVIC84600G": ("Omnicomprensivo Croce-Nobile-Amundsen", r"CROCE\s*NOBILE\s*AMUNDSEN"),
    "AVIC864005": ("IC Alessandro Manzoni", r"A\.?\s*MANZONI"),
    "AVIC86600R": ("IC Giovanni XXIII-Parini", r"GIOVANNI XXIII-?\s*G?\.?\s*PARINI"),
    "AVIC87900V": ("IC Michele Pironti", r"MICHELE PIRONTI"),
    "AVIC880003": ("IC Galiani", r"A\.?\s*F\.?\s*GALIANI"),
    # Napoli: circoli didattici
    "NAEE15800G": ("2° Circolo Didattico", r""),
    "NAEE177001": ("1° Circolo Didattico", r""),
    "NAEE18500X": ("1° Circolo Didattico Raffaele Arfè", r"RAFFAELE ARFE'?"),
    "NAEE18700G": ("Circolo Didattico", r""),
    "NAEE191007": ("4° Circolo Didattico Cesaro", r"C\.?\s*N\.?\s*CESARO|CESARO"),
    "NAEE21400P": ("2° Circolo Didattico Don Minzoni", r""),
    "NAEE21900T": ("Circolo Didattico Eduardo De Filippo", r"E\.?\s*DE FILIPPO"),
    "NAEE220002": ("2° Circolo Didattico Celentano", r"CELENTANO"),
    "NAEE32300A": ("3° Circolo Didattico Madre Teresa di Calcutta", r""),
    # Napoli: istituti comprensivi
    "NAIC80300C": ("IC Padre Arturo D'Onofrio", r"PADRE ARTURO D'ONOFRIO"),
    "NAIC847006": ("IC Denza", r"DENZA"),
    "NAIC850002": ("IC Custra", r"CUSTRA"),
    "NAIC85300D": ("IC Mascolo-De Curtis", r"MASCOLO"),
    "NAIC855005": ("IC D'Avino", r"D'AVINO"),
    "NAIC85700R": ("IC Serao", r"SERAO"),
    "NAIC863004": ("IC Eduardo De Filippo", r"E\.?\s*DE FILIPPO"),
    "NAIC86400X": ("IC Paride Del Pozzo", r"PARIDE DEL POZZO"),
    "NAIC868007": ("IC Carducci", r"CARDUCCI"),
    "NAIC87500A": ("IC Falcone", r"FALCONE"),
    "NAIC87900N": ("IC Viviani", r"VIVIANI"),
    "NAIC898003": ("IC De Nicola", r"S\.?\s*M\.?\s*DE NICOLA|DE NICOLA"),
    "NAIC8AH006": ("IC Di Capua", r"DI CAPUA"),
    "NAIC8AJ002": ("IC Aldo Moro", r"ALDO MORO|MORO"),
    "NAIC8AK00G": ("IC 2 Leonardo da Vinci", r"LEONARDO DA VINCI"),
    "NAIC8AL00B": ("IC 1 Tenente De Rosa", r"TEN\.?\s*DE ROSA"),
    "NAIC8AM007": ("IC 2 Caulino", r"(?:F\.?\s*)?CAULINO"),
    "NAIC8AN003": ("IC De Filippo", r"DE FILIPPO"),
    "NAIC8AP00V": ("IC Mameli", r"MAMELI"),
    "NAIC8AS00A": ("IC Pellico-Iozzino", r"PELLICO|IOZZINO"),
    "NAIC8B5009": ("IC Amedeo Maiuri", r"A(MEDEO|\.)?\s*MAIURI"),
    "NAIC8B6005": ("IC Ernesto Borrelli", r"E\.?\s*BORRELLI"),
    "NAIC8B7001": ("IC Forzati-De Curtis", r"FORZATI"),
    "NAIC8B800R": ("IC San Giovanni Bosco-De Sica", r"SAN G\.?\s*BOSCO"),
    "NAIC8BC00N": ("IC Bruno-Fiore-Sanseverino", r"G\.?\s*BRUNO\s*-?\s*FIORE"),
    "NAIC8BE009": ("IC Pacinotti", r"PACINOTTI"),
    "NAIC8BF005": ("IC San Gennarello", r"S\.?\s*GENNARELLO"),
    "NAIC8BG001": ("IC Alfieri", r"ALFIERI"),
    "NAIC8BK00T": ("IC Giampietro-Romano", r"GIAMPIETRO\s*-?\s*ROMANO"),
    "NAIC8BM00D": ("IC Angioletti", r"ANGIOLETTI"),
    "NAIC8BP001": ("IC 3", r""),
    "NAIC8C3008": ("IC Giusti", r"GIUSTI"),
    "NAIC8C4004": ("IC 3 Don Bosco-D'Assisi", r""),
    "NAIC8C600Q": ("IC 1 De Luca Picione-Giordano", r"DE LUCA PICIONE"),
    "NAIC8CA00L": ("IC 1 Don Bosco-Melloni", r""),
    "NAIC8CC008": ("IC 4 De Lauzieres", r""),
    "NAIC8CG00G": ("IC D'Aosta", r"D'AOSTA"),
    "NAIC8CJ00L": ("IC Mimmo Beneventano", r"M\.?\s*BENEVENTANO|BENEVENTANO"),
    "NAIC8CL008": ("IC 1 Mazza-Colamarino", r""),
    "NAIC8CQ00B": ("IC 1 De Curtis", r"A\.?\s*DE CURTIS"),
    "NAIC8CR007": ("IC 2 Vincenzo Russo", r"V\.?\s*RUSSO|RUSSO"),
    "NAIC8CS00C": ("IC De Nicola-Sasso", r""),
    "NAIC8CT008": ("IC Donizetti", r"G\.?\s*DONIZETTI"),
    "NAIC8D2003": ("IC 1 Cangemi", r""),
    "NAIC8D300V": ("IC 2 Francesco Dati", r"DATI"),
    "NAIC8DA007": ("IC 3 De Curtis-Ungaretti", r"DE\s*CURTIS\s*-?\s*UNGAR\w*"),
    "NAIC8DF00A": ("IC Falcone-Scauda", r"FALCONE"),
    "NAIC8DH002": ("IC 2 Panzini", r"PANZINI"),
    "NAIC8DJ007": ("IC 5 Karol Wojtyla", r"KAROL\s*WOJTYLA"),
    "NAIC8DT00V": ("IC 2 Milani-Aliperti", r"ALIPERTI"),
    "NAIC8E6001": ("IC 3 Staglie-Parco Imperiale", r""),
    "NAIC8ED009": ("IC 3 Castaldi-Rodari", r""),
    "NAIC8EJ00T": ("IC 1 Prisco", r"PRISCO"),
    "NAIC8EK00N": ("IC De Filippo-De Ruggiero", r"DE RUGGIERO"),
    "NAIC8EX00R": ("IC Bovio-Pontillo-Pascoli", r""),
    "NAIC8EZ00C": ("IC Mercogliano-Guadagni", r"MERCOGLIANO\s*-?\s*GUADAGNI"),
    "NAIC8F9003": ("IC 1 Capoluogo", r""),
    "NAIC8FD00X": ("IC Massimo Troisi", r""),
    "NAIC8FE00Q": ("IC 2 Massaia", r""),
    "NAIC8FF00G": ("IC 3 Dorso", r""),
    "NAIC8FG00B": ("IC 4 Stanziale", r""),
    "NAIC8FJ00C": ("IC 3 Ceschelli", r""),
    "NAIC8FQ007": ("IC Omodeo-Beethoven", r"OMODEO\s*-?\s*BEETHOVEN|OMODEO"),
    "NAIC8FV00Q": ("IC 5 Santagata", r""),
    "NAIC8FW00G": ("IC 2 Da Vinci-Comes", r""),
    "NAIC8FX00B": ("IC Roccarainola", r""),
    "NAIC8FY007": ("IC Leopardi-Parini", r""),
    "NAIC8G1003": ("IC 1 D'Acquisto-Leone", r""),
    "NAIC8G7002": ("IC Siani-Alighieri", r""),
    "NAIC8G800T": ("IC Pascoli-Siani", r""),
    "NAIC8GF006": ("IC D'Angiò-Via Vesuvio", r""),
    "NAIC8GG002": ("IC Giambattista della Porta", r"G\.?\s*B\.?\s*DELLA PORTA"),
    "NAIC8GK00V": ("IC Cozzolino-D'Avino", r"COZZOLINO\s*-?\s*(D'AVINO)?"),
    "NAIC8GL00P": ("IC 5 Maiuri", r""),
    "NAIC8GU00E": ("IC D'Assisi", r"D'ASSISI"),
    "NAIC8GX002": ("IC 1 Rodinò", r""),
    "NAIC8GY00T": ("IC 2 Giampaglia-Iaccarino", r""),
    "NAIC8H3009": ("IC Don Milani-Leopardi", r""),
    "NAIC8H4005": ("IC Sauro-Morelli", r""),
    "NAIC8H9008": ("IC Ciccone", r""),
    "NAIC8HC009": ("IC Merliano-Tansillo-Vitale", r""),
    "NAIC8HD005": ("IC 1 Cecchi-Stabiae", r""),
    "NAIC8HE001": ("IC San Marco-Bonito-Cosenza", r""),
    "NAIC8HH00C": ("IC 3 Bosco-Villa", r""),
    "NAIC8HJ00N": ("IC De Curtis-Ragazzi d'Europa", r""),
    "NAIC8HK00D": ("IC Salvemini", r""),
    "NAIC8HM005": ("IC Ammendola-De Amicis", r""),
    "NAIC8HR008": ("IC Ungaretti-Fucini", r""),
    "NAIC8HS00D": ("IC Lizzadri-Roncalli", r""),
    "NAIC8HW00R": ("IC 1 Capoluogo", r""),
    "NAIC8HX00L": ("IC Brusciano Capoluogo", r""),
    "NAIC8JC003": ("IC 2 Ponte-Omero", r""),
    "NAIC8JD00V": ("IC 3 Catullo", r""),
    "NAIC8JE00P": ("IC 4 Falcone", r""),
    # Salerno
    "SAEE102002": ("1° Circolo Didattico", r""),
    "SAEE16100T": ("1° Circolo Didattico Anna Ferrara", r""),
    "SAEE16300D": ("3° Circolo Didattico Rosa Pisacane", r""),
    "SAIC84600R": ("IC Lanzara", r""),
    "SAIC88200X": ("IC Samuele Falco", r""),
    "SAIC88300Q": ("IC Tommaso Anardi", r""),
    "SAIC89800D": ("IC Siano-Bracigliano", r""),
    "SAIC899009": ("IC San Valentino Torio", r""),
    "SAIC8A300D": ("IC Carducci-Trezza", r""),
    "SAIC8A5005": ("IC Sant'Alfonso de' Liguori", r""),
    "SAIC8A900C": ("IC San Marzano sul Sarno", r""),
    "SAIC8B000L": ("IC Don Bosco", r""),
    "SAIC8B100C": ("IC Santa Lucia", r""),
    "SAIC8B2008": ("IC San Nicola-Pregiato", r""),
    "SAIC8B8007": ("IC Fresa-Pascoli", r""),
    "SAIC8BA00C": ("IC Eduardo De Filippo", r""),
    "SAIC8BB008": ("IC De Amicis-Baccelli", r""),
    "SAIC8BD00X": ("IC Vassalluzzo", r""),
    "SAIC8BN00Q": ("IC Don Enrico Smaldone", r""),
    "SAIC8BR003": ("IC 5", r""),
    "SAIC8BS008": ("IC 1 Solimena", r""),
    "SAIC8BT004": ("IC 2", r""),
    "SAIC8BU00X": ("IC 3 Massimo Li Pira", r""),
    "SAIC8BV00Q": ("IC 4 Ilaria Alpi", r""),
    "SAIC8BW00G": ("IC Amendola", r""),
    "SAIC8BX00B": ("IC Antonio Esposito", r""),
    "SAIC8BZ003": ("IC Balzico-Giovanni XXIII", r""),
    "SAIC8CA003": ("IC Senatore-Martiri", r""),
    "SAIC8CB00V": ("IC Criscuolo", r""),
    "SAIC8CC00P": ("IC San Tommaso d'Aquino", r""),
    "SAIC8CD00E": ("IC 2 Trotula de Ruggiero", r""),
    "SAIC8CK00V": ("IC Nuceria", r""),
    "SAIC8CL00P": ("IC 1 Opromolla-Sant'Alfonso", r""),
    "SAIC8CM00E": ("IC 3 Galvani", r""),
}
